### ISSUE TITLE
Docker and NLP suite runner downloaded, however cannot open NLP suite runner afterwards

### ISSUE THREAD

**Issue by cpei22** [NLP-Suite/nlp-suite-runner#11]
I've followed the github download process yet when I'm at this step "To run the NLP Suite Runner, double click the binary/exe to start it." , I double click the runner and nothing happens. I have docker desktop opened and installed as well.

I am on windows x64 bit. 

![image](https://github.com/NLP-Suite/nlp-suite-runner/assets/112918264/9fa429be-1553-475d-9ba3-7cfcbd8c492f)

**Comment by RafaelPiloto10** [comment]
Hi @cpei22, does a window pop up with some text? If so, please take a screenshot of that.

**Comment by cpei22** [comment]
No texts, I double click the runner, a window briefly pops up and then nothing happens 

![image](https://github.com/NLP-Suite/nlp-suite-runner/assets/112918264/4f5113d6-00e1-4ec4-a261-e3bbc35c1d9a)

**Comment by cpei22** [comment]
I believe the issue was my storage ran out of space, however, I had a little over the 10GB of space prior to download. Maybe the requirements are closer to 13-15 GB

**Comment by RafaelPiloto10** [comment]
Hi @cpei22, did that fix the issue? If not -- try downloading the latest version of the NLP Suite Runner. I have made it so that the window stays open in case there are any errors. Thanks
