### ISSUE TITLE
404 Not Found Error with Link

### ISSUE THREAD

**Issue by gabrielischwartz** [NLP-Suite/nlp-suite-runner#5]
<img width="1087" alt="Screenshot 2024-04-20 at 12 43 02 PM" src="https://github.com/NLP-Suite/nlp-suite-runner/assets/156736610/66124e42-c6a0-4b7b-82f9-d4e8ad956257">
<img width="390" alt="Screenshot 2024-04-20 at 12 44 22 PM" src="https://github.com/NLP-Suite/nlp-suite-runner/assets/156736610/ba2f4ff8-50a4-43ad-b2a1-7d00719cd1dc">

When I try to run the NLP Suite on my Mac this error occurs

**Comment by gabrielischwartz** [comment]
<img width="1300" alt="Screenshot 2024-04-20 at 3 35 00 PM" src="https://github.com/NLP-Suite/nlp-suite-runner/assets/156736610/99b66491-538b-4a32-ad48-1ec622046df4">
I just tried the same thing again, but got this error.

**Comment by RafaelPiloto10** [comment]
Hi @gabrielischwartz, make sure the Runner is active. You can start from a clean slate by deleting all your Docker containers in the Docker Desktop GUI. Then open the runner again. If they are active and you are still getting this error, please open each Docker container and head over to the logs tab and take screenshots of those. Thanks.

**Comment by gabrielischwartz** [comment]
Hi, I deleted all the images, and tried again and then it started to work. Thank you for your help.
